### ISSUE TITLE
Generalizing Rich Command Usage

### ISSUE THREAD

**Issue by QuaintMako** [files-community/Files#11481]
### Description

Thanks to @cinqmilleans' job, Files has now a cleaner way to handle commands across the solution. Rich commands now need to be implemented throughtout the whole solution.

This issue is used to keep track of which commands are made into Rich Commands.

### Concerned code

The following commands must be transformed into Rich Commands (See `BaseLayoutCommandsViewModel`, `ContextFlyoutItemHelper` and `ToolbarViewModel`):

- [x] Clear Selection (#11502)
- [x] Close Selected Tab (#11916)
- [x] Close Pane (#12002)
- [x] Compress Into Archive (#11572)
- [x] Compress Into Seven Zip (#11572)
- [x] Compress Into Zip (#11572)
- [x] Copy Item (#11504)
- [x] Copy Path Of Selected Items (#11774)
- [ ] Create Folder With Selection
- [x] Create New File
- [x] Create New Folder (#11493)
- [x] Create Shortcut (#11493)
- [x] Create Shortcut From Dialog (#11493)
- [x] Cut Item (#11504)
- [x] Decompress Archive (#11723)
- [x] Decompress Archive Here (#11723)
- [x] Decompress Archive To Child Folder (#11723)
- [x] Delete Item (#11504)
- [x] Duplicate Tab (#11596)
- [x] Empty Recycle Bin (#11415 )
- [x] Enter compact overlay (#11821)
- [x] Exit compact overlay (#11821)
- [x] Format Drive #11831
- [x] Gridview Size Decrease (#11678)
- [x] Gridview Size Increase (#11678)
- [x] Group Layer Sort (#11678)
- [x] Install Font (#11780)
- [x] Install Inf Driver (#11812)
- [x] Invert Selection (#11502)
- [x] Multi-Selection (#11502)
- [x] Navigate back (#11829)
- [x] Navigate forward (#11829)
- [x] Navigate up (#11829)
- [x] Navigate To Next Tab (#11916)
- [x] - [x] Navigate To Previous Tab (#11916)
- [ ] Open Directory In New Pane
- [ ] Open Directory In New Tab
- [x] Open File Location
- [ ] Open In New Window Item
- [x] Open In Terminal (#11445)
- [x] Open Item (#11667)
- [x] Open Item With Application Picker (#11667)
- [x] Open New Tab (#11596)
- [x] Open Parent Folder (#11667)
- [x] Open new pane (#12002)
- [x] Open settings #11846
- [x] Paste Items From Clipboard (#11670)
- [x] Pin Directory To Favorite
- [x] Play All (#12017)
- [x] Quick Look (#11771)
- [x] Redo (#12017)
- [x] Refresh #11807
- [x] Rename Item #11861
- [x] Reopen Tab (#11833)
- [x] Restore Item (#11472)
- [x] Restore Selection Recycle Bin (#11472)
- [x] Rotate Image Left (#11633)
- [x] Rotate Image Right (#11633)
- [x] Run As Admin (#11581)
- [x] Run As Another User (#11581)
- [x] Run With Powershell (#11914)
- [x] Search Unindexed Items (#12074)
- [x] Select All (#11502)
- [ ] Send to
- [x] Set As Lockscreen Background (#11563)
- [x] Set As Slideshow Item(#11563)
- [x] Set as Desktop Background(#11563)
- [x] Show Folder Properties (#11915)
- [x] Show Properties (#11915)
- [ ] Show/hide dot files
- [x] Share file (#11827)
- [x] Sidebar Pin Item (#11492)
- [x] Sidebar Unpin Item (#11492)
- [x] Toggle Preview Pane (#11578)
- [x] Toggle Sidebar #11847
- [x] Undo (#12017)
- [x] Unpin Directory From Favorite
- [x] Unpin Item From Start

### Gains

- A more cohesive code.
- The ability to call commands easily from anywhere in the code.

### Requirements

- Each of the commands previously cited have been transformed into Rich Commands.
- The previous implementations of the commands are cleaned up.

**Comment by yaira2** [comment]
Thank you for putting this together!

**Comment by hecksmosis** [comment]
I'll do the sidebar pinned item ones

**Comment by hecksmosis** [comment]
I'm working on some of these slowly

**Comment by QuaintMako** [comment]
I'm tackling the 'Set As...' trio on my side.

**Comment by QuaintMako** [comment]
Once we're done with implementing all the commands, we'll need to remember to do a round of cleaning (regrouping the commands together, make sure they are stored inside the appropriate folders, make sure there is no leftovers from the former implementations etc...)

**Comment by hecksmosis** [comment]
Fyi, copy cut and delete heve already been implemented in #11504

**Comment by hishitetsu** [comment]
Gridview Size Decrease and Gridview Size Increase have already been implemented in #11678.

**Comment by cinqmilleans** [comment]
DuplicateTab/ Paste Items From Clipboard/(Pin/Unpin) Directory (To/From) (Favorites/Start) are implemented. 
DragOver/Drop/Item Pointer Pressed must not be a command because they are only accessible by mouse (by nature).
A command to open the context menu would be handy.

**Comment by QuaintMako** [comment]
Thanks for the update @cinqmilleans, I need to go through the code in more details to check out what needs to be made as commands. I'll change the checklist with your information!

**Comment by hecksmosis** [comment]
Shouldn't we make Close Tab a command?

**Comment by yaira2** [comment]
> Shouldn't we make Close Tab a command?

Yes, with the `ctrl` + `w` shortcut.

**Comment by QuaintMako** [comment]
I believe this has been closed by accident, reoppening it since there is still a few commands to finish.

**Comment by hecksmosis** [comment]
I think we would need a new context like TabsContext, I'll try to implement it

**Comment by hecksmosis** [comment]
I'll do format drive

**Comment by QuaintMako** [comment]
I am currently looking into Show Properties and Create New File

**Comment by hishitetsu** [comment]
Wouldn't undo and redo be rich commands?

**Comment by QuaintMako** [comment]
> Wouldn't undo and redo be rich commands?

It would, I need to get back into the code and remap the commands to make as RC, hadn't thought about the inner tabs commands and when doing it.

**Comment by ferrariofilippo** [comment]
I'm working on `Reopen closed tabs` and `Toggle sidebar`. @QuaintMako can you add them to the list?

**Comment by yaira2** [comment]
> View Release Now

Is this supposed to be "Release notes"?

**Comment by 0x5bfa** [comment]
I'm working on #11914 & #11915. @QuaintMako can you add it to the list?

**Comment by hecksmosis** [comment]
I'll look into open directory in new tab/Pane
