### ISSUE TITLE
Tracking: Improve SidebarPinnedModel with support for child items

### ISSUE THREAD

**Issue by duke7553** [files-community/Files#3246]
This issue will track the pre-requisite work done in order to allow manipulation of child sidebar items.

- [ ] Change default item addition in the model to add root items and their respective default children (if applicable)
- [ ] Support getting root items only
- [ ] Support getting child items from a specified header item of a certain type
- [ ] Update all methods to accept INavigationControlItem as the argument rather than a path string
- [ ] Make all overloads of IndexOfItem() return an index specific to the root node's collection of children
- [ ] Ensure each INavigationControlItem-derived model doesn't have any references to Windows.UI.*
- [ ] Ensure the changes are compatible with the existing JSON 
- [ ] Get changes approved by original implementor (probably @tsvietOK)

_More work items coming soon_

**Comment by duke7553** [comment]
Closing this because I decided to use a different method altogether that requires less of this work.
