### ISSUE TITLE
[Tracking] Interaction tests for Files

### ISSUE THREAD

**Issue by chingucoding** [files-community/Files#7236]
With #7234 , we are adding interaction tests to Files. This issue is for tracking the changes that still need to be done:
* [x] Move Files, Files.Package ... into a `src` folder and the test projects into a `tests` folder
* [ ] Add running interaction tests to CI
* [ ] Improve interaction test coverage (optional)
* [x] Anything else?

**Comment by marcelwgn** [comment]
@yair100 FYI

**Comment by yaichenbaum** [comment]
@chingucoding support for testing in different languages?

**Comment by chingucoding** [comment]
> @chingucoding support for testing in different languages?

Do you mean to write the tests language agnostic? If so, the current PR solves this through automation IDs.

Or do you mean to write tests that actively test the app with different languages?

**Comment by yaichenbaum** [comment]
> Do you mean to write the tests language agnostic? If so, the current PR solves this through automation IDs.

That's what I meant 👍
