### ISSUE TITLE
Tracking of keyboard/mouse shortcuts

### ISSUE THREAD

**Issue by ghost** [files-community/Files#9]
- [x] alt+enter to show the properties for the current selected folder(s) and/or file(s) 
- [x] ctrl+n for new window
- [x]  CTRL + TAB to cycle between tabs
- [x] ctrl+w to close tab
- [x]  Delete key for delete
- [x] alt+f, alt+h, alt+l for file/home/layout ribbons
- [x]  ALT + LEFT , ALT + RIGHT for history navigation
- [x]  CTRL + SHIFT + N for new item
- [x]  Enter button to open an item
- [x]  CTRL + C, CTRL + V, CTRL + F for their respective commands
- [x]  CTRL + T for new tab
- [x] ctrl+[shift]+tab to switch tabs
- [x] Typing a letter to jump to a file/folder
- [x] ctrl+r to refresh
- [x] ctrl+f4 to close tab
- [x] [?] Mouse side buttons for history navigation
- [x] CTRL + L to place focus in the address bar
- [ ] ctrl+shift+t to restore a recently closed tab or a recently closed window with all its tabs.
- [x] alt+d for address bar (address since old)
- [x] the file pane should be selected by default, otherwise hotkeys like ctrl+a don't work.
- [ ] esc to defocus search box.
- [ ] CTRL + E to place focus in the search bar
- [x] Ctrl + scroll up: Grid view
- [x] Ctrl + scroll down: List view

**Comment by StrongholdFan** [comment]
I want to add something to this issue: My mouse (Logitech G603) features side-buttons in order to go back and forth. These buttons don't work in File UWP yet and I'd would be really great, if mouses that have such buttons are supported. Hope the issue got clear. Thanks for the great app! :)

**Comment by duke7553** [comment]
My checklist:
- [ ] Type to jump to a file/folder

- [x] Delete key for delete 

- [ ] Alt + LEFT , Alt + RIGHT for history navigation

**Comment by mtourj** [comment]
Don't know if this is fixed yet, but I think Alt + LEFT and Alt + RIGHT is a better way to go when navigating history. It's used in the original explorer and in most web browsers. Also allows for future group-selection when icons are in a tile layout (I assume something like that should be implemented in the future)

**Comment by eduardopatricio** [comment]
Ctrl + shift + n to create a new folder would be great to have (essential for me)

**Comment by yaichenbaum** [comment]
- [ ] ctrl + c (copy)
- [ ] ctrl + v (paste)
- [ ] ctrl + f (put focus on search box)

**Comment by duke7553** [comment]
I updated my list

**Comment by yaichenbaum** [comment]
Instead of ctrl + shift + a for a new item it should be ctrl + shift + n as @eduardopatricio said, that's the current behavior in file explorer.

**Comment by duke7553** [comment]
@yaichenbaum Correct, that was a mistake

**Comment by duke7553** [comment]
@yaichenbaum I actually discovered the CTRL + C (Copy) accelerator was almost always blocked by a copy function specific to the row's text. After removing this, the event should always work as expected now. Oh, and I also **finally** removed the ugly black focus indicator around the DataGrid cells to match Windows Explorer. These changes will be in the next snapshot.

**Comment by yaichenbaum** [comment]
That's awesome, I kind of assumed it wasn't that simple to remove that black focus indicator and even took a quick look to see if I can tweak it but did not see a way. I love seeing the progress you are making.

**Comment by duke7553** [comment]
@yaichenbaum I thought that too until I realized I can simply override the hardcoded style of the DataGrid.
 ```
<controls:DataGrid.Resources>
        <SolidColorBrush x:Key="DataGridCellFocusVisualPrimaryBrush" Color="Transparent"/>
        <SolidColorBrush x:Key="DataGridCellFocusVisualSecondaryBrush" Color="Transparent"/> 
</controls:DataGrid.Resources>
```

**Comment by yaichenbaum** [comment]
Can you add ctrl + w to close a tab and ctrl + tab to switch between tabs to the list?

**Comment by yaichenbaum** [comment]
Is it possible to add ctrl + shift + del to permanently delete a file or folder?

**Comment by shaykalyan** [comment]
May I add 
* **CTRL + L** to place focus in the address bar
* **CTRL + E** to place focus in the search bar

**Comment by yaichenbaum** [comment]
@shaykalyan thanks for the feedback, since this is how the current file explorer functions we will add these in, in the future.

**Comment by Efreak** [comment]
Perhaps have a large checklist at the top of this issue to keep track? I've got some suggestions here:

- history next/prev keyboard keys
- ctrl+n for new window
- alt+d for address bar (ad**d**ress since old)
- f6 for address bar
- ctrl+[shift]+tab to switch tabs
- ctrl+w to close tab
- ctrl+f4 to close tab
- in address bar, show full path once clicked, not simple 'downloads'. This currently makes it hard to copy the path of the current folder without using the toolbar button.
- the file pane should be selected by default, otherwise hotkeys like ctrl+a don't work.
- esc to defocus search box.
- ctrl+r to refresh
- alt+f, alt+h, alt+l for file/home/layout ribbons

**Comment by szaimen** [comment]
I would really like to get these:
- [ ] ctrl+n for new window
- [ ] ctrl+[shift]+tab to switch tabs
- [ ] ctrl+w to close tab
- [ ] ctrl+r to refresh
- [ ] ctrl+alt to show the properties for the current selected folder(s) and or file(s) (https://github.com/duke7553/files-uwp/issues/259)

**Comment by szaimen** [comment]
@yaichenbaum I looked at your list and found three times:

> CTRL + TAB to cycle between tabs

Otherwise really nice list!

**Comment by yaichenbaum** [comment]
@szaimen Thanks for pointing that out, CTRL + TAB and CTRL + SHIFT + TAB are two shortcuts to do the same thing so thats why they are both there, I removed the other duplicates though.

**Comment by szaimen** [comment]
Possible additional shortcuts to be considered could be:
- [ ] a shortcut for renaming? (don't know if there is already an existing one, maybe you should think about a shortcut that makes sense if nothing exists. I have currently no idea for that)
- [ ] backspace for the last directory
- [ ] alt+UP for going up in directory?

Other shortcuts that are inspired by macos and could work at least in the list view since they have no function there in the moment and could be used to navigate folders and files (in theorie much easier then the current situation):
- [ ] RIGHT to open a folder or file (additionally to enter)
- [ ] LEFT to go back to the last directory or for going up in directory?

**Comment by yaichenbaum** [comment]
@szaimen 
There is a shortcut for renaming - F2
Backspace is already implemented
Alt + Up is already implemented but it only works when the file area is focused at the moment.
There will be issues with "right" and "left" since when there is a grid view for items and those keys will be needed to switch focus on files and folders with the keyboard.

**Comment by szaimen** [comment]
> There will be issues with "right" and "left" since when there is a grid view for items and those keys will be needed to switch focus on files and folders with the keyboard.

Yes, so maybe just adding these shortcuts to the list view?

**Comment by szaimen** [comment]
> There is a shortcut for renaming already implemented - F2

I don't know if an Function-key is appropriate in the current time since I know many devices and keyboards that have other shortcuts on these buttons as default. So maybe it would be appropriate to consider another additional one maybe with "alt" + "another key" or "ctrl" + "another key"?

**Comment by yaichenbaum** [comment]
F2 is the behavior in File Explorer, about having other shortcuts on those keys that what the FN key is for.

**Comment by szaimen** [comment]
> F2 is the behavior in File Explorer, about having other shortcuts on those keys that what the FN key is for.

Yes, I know that but I just find it inconsistent to use. 
(it is bad to reach and at least for me just to use in combination with the fn-key.) 

The only shortcut, that I could imagine since almost every combination is already used is "ctrl+q" but this has other features in other programs. 
Maybe also "ctrl+e" could be considered -> the "e" could stand for editing (aka renaming), but is already planned for searching (although it don't make sense imo to have ctrl+f and ctrl+e for the same behavoir...)

But if you don't want it, I will accept this.

**Comment by R3voA3** [comment]
> [?] Mouse side buttons for history navigation
Remarks: Attempt to map these buttons to a key failed to fire the event with my mouse.

Any update on that? 

Also, can this issue be renamed to keyboard / mouse shortcuts? I actually wanted to create an issue about mouse navigation because I didn't find one at first.

**Comment by yaichenbaum** [comment]
@duke7553 Can we can @R3voA3's request in the next update?

**Comment by duke7553** [comment]
I would like to, but I'm unsure which key code represents the mouse side buttons.

**Comment by yaichenbaum** [comment]
@R3voA3 I believe I got it setup for navigating with the mouse buttons but I don't have a mouse to test with, are you interested in building from the source code and testing?
If you are able to test this out, you should use the `v07.1-changes` branch since that is where the changes have been made.

**Comment by R3voA3** [comment]
@yaichenbaum I am getting this error 
![image](https://user-images.githubusercontent.com/17484252/73366087-a4ce9980-42ad-11ea-8a13-373e4f501fcf.png) shortly after I started the debugging. 
Since I have no clue how to fix that I can not test the new changes

**Comment by yaichenbaum** [comment]
@R3voA3 I would try enabling file permissions in the privacy setting in Windows.

**Comment by R3voA3** [comment]
Thanks for the tip, but that didn't help.

**Comment by yaichenbaum** [comment]
@R3voA3 Make sure to use the `v07.1-changes` branch, it looks like you are using master.

**Comment by R3voA3** [comment]
I cloned the 07.1 branch into visual studio.

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/73377082-7be9dc80-428c-11ea-807c-79588c6b33ec.png)
You can switch to it on the bottom right of the status bar in Visual Studio.

**Comment by yaichenbaum** [comment]
@R3voA3 I realized the issue is that you need to select Files.Package as the startup project.
![image](https://user-images.githubusercontent.com/39923744/73379900-19470f80-4291-11ea-8f2a-38f1e4c8e174.png)

**Comment by R3voA3** [comment]
Alright, now it's working. 

Unfortunately, the mouse navigation doesn't seem to work. Pressing the side buttons when hovering over a folder, only opens them.

**Comment by yaichenbaum** [comment]
Ok, thanks for letting me know. I will need to spend some more time on this.

**Comment by yaichenbaum** [comment]
Moving this from #387 

The biggest issue I find with the usability of Files UWP is the missing controls that I'm used to.
these are the controls I'd like to see added:
- Back and forward buttons on the mouse to be integrated.
- Middle click (clicking scroll wheel) to open in new tab.
- CTRL+MiddleClick or Shift+MiddleClick to open in new window.

**Comment by R3voA3** [comment]
@yaichenbaum There is an app on the MS Store called Math Solver (https://www.microsoft.com/store/productId/9WZDNCRFJ47X) which uses mouse navigation. Maybe you can get in contact with him?

**Comment by yaichenbaum** [comment]
@R3voA3 I have the right code, I just need to get the events in the right place and the problem is I need a mouse to test with 😀
I will see if I can get my hands on one in the near future so I can get this working.

**Comment by R3voA3** [comment]
I can test it again, if you made some changes.

**Comment by yaichenbaum** [comment]
@R3voA3 thanks for the offer, I will let you know when there is something new to test.

**Comment by yaichenbaum** [comment]
@R3voA3 I made a small change, I don't know if it will work or not but feel free to try again.

**Comment by R3voA3** [comment]
@yaichenbaum Alright, navigating back works, although there is a noticeable delay between the pressing of the button and the actually navigation. Navigating forth doesn't seem to work yet.

**Comment by yaichenbaum** [comment]
@R3voA3 Can you test again if it's working to use the mouse buttons for navigation?

**Comment by R3voA3** [comment]
Works fine with the latest Store version. @yaichenbaum

**Comment by imReker** [comment]
In v0.9.2.0, alt+left/right not work correctly, sometimes they behavior like TAB key pressed and the focus moved.
And mouse back/forward button will make a left click event in window.

**Comment by AbelTheGeorge** [comment]
Can there be an option to customize the current keyboard shortcuts?

**Comment by yaichenbaum** [comment]
@AbelTheGeorge Customizing keyboard shortcuts is something we are looking into supporting.

**Comment by XPoppyX** [comment]
> Customizing keyboard shortcuts is something we are looking into supporting.

similar to microsoft edge chromium

![Anotación 2020-08-02 205109](https://user-images.githubusercontent.com/61259627/89137108-d1859700-d504-11ea-8516-eac9c3e33027.png) ![Anotación 2020-08-02 210222](https://user-images.githubusercontent.com/61259627/89137066-9e430800-d504-11ea-82f1-7641b23c9998.png)

**Comment by yaichenbaum** [comment]
@XPoppyX Can you open a seperate issue with the concept you shared?

**Comment by XPoppyX** [comment]
> @XPoppyX Can you open a seperate issue with the concept you shared?

ok

**Comment by ZoroNasr** [comment]
Whenever I try to select multiple files using the Ctrl+space bar, it doesn't work, only Ctrl+left mouse click.

**Comment by yaichenbaum** [comment]
With the exception of one shortcut #2117, all items in this issue have been resolved. Moving forward, requests for new shortcuts should get their own issue.
